#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-Font-Awesome
Version  : 4.7.0.0
Release  : 17
URL      : http://pypi.debian.net/XStatic-Font-Awesome/XStatic-Font-Awesome-4.7.0.0.tar.gz
Source0  : http://pypi.debian.net/XStatic-Font-Awesome/XStatic-Font-Awesome-4.7.0.0.tar.gz
Summary  : Font-Awesome 4.7.0 (XStatic packaging standard)
Group    : Development/Tools
License  : 1.1 MIT OFL OFL-1.1 SIL
Requires: XStatic-Font-Awesome-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
XStatic-Font-Awesome
--------------
Font Awesome icons packaged for setuptools (easy_install) / pip.

%package python
Summary: python components for the XStatic-Font-Awesome package.
Group: Default
Provides: xstatic-font-awesome-python

%description python
python components for the XStatic-Font-Awesome package.


%prep
%setup -q -n XStatic-Font-Awesome-4.7.0.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1488596048
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1488596048
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
